alias cp='nocorrect cp -i'
alias ebuild='nocorrect ebuild'
alias gist='nocorrect gist'
alias heroku='nocorrect heroku'
alias hpodder='nocorrect hpodder'
alias man='nocorrect man'
alias mkdir='nocorrect mkdir'
alias mv='nocorrect mv -i'
alias mysql='nocorrect mysql'
alias sudo='nocorrect sudo'
alias which='nocorrect which'
alias touch='nocorrect touch'

CORRECT_IGNORE_FILE='.*'
setopt correct_all   # CORRECT_IGNORE_FILE to ignore
